version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    restart: always
    ports:
      - "10000:10000" # Render default port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cvfbks8fnakc739mi7ag-a.singapore-postgres.render.com:5432/todo_db_izo7
      SPRING_DATASOURCE_USERNAME: todo_db_izo7_user
      SPRING_DATASOURCE_PASSWORD: WnK0FUSTpDlw76BP4l7sxsVqFkRlYups
      PORT: 10000
